// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $MinicartAdd from "./islands/MinicartAdd.tsx";
import * as $Sort from "./islands/Sort.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Filters.tsx": $Filters,
    "./islands/MinicartAdd.tsx": $MinicartAdd,
    "./islands/Sort.tsx": $Sort,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
