// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/minicart/submit.ts";
import * as $$$$$$$$$1 from "./actions/wishlist/submit.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/ai-assistants.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/implementation.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/typesense.ts";
import * as $$$$$$$$$$$5 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$6 from "./apps/site.ts";
import * as $$$0 from "./loaders/availableIcons.ts";
import * as $$$1 from "./loaders/icons.ts";
import * as $$$2 from "./loaders/minicart.ts";
import * as $$$3 from "./loaders/simulateCart.ts";
import * as $$$4 from "./loaders/user.ts";
import * as $$$5 from "./loaders/wishlist.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Category/CarouselBrand.tsx";
import * as $$$$$$2 from "./sections/Category/CarouselCategory.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$5 from "./sections/Component.tsx";
import * as $$$$$$6 from "./sections/Content/Faq.tsx";
import * as $$$$$$7 from "./sections/Content/Hero.tsx";
import * as $$$$$$8 from "./sections/Content/Intro.tsx";
import * as $$$$$$9 from "./sections/Content/Logos.tsx";
import * as $$$$$$10 from "./sections/Content/ShowCaseCounter.tsx";
import * as $$$$$$11 from "./sections/Footer/Footer.tsx";
import * as $$$$$$12 from "./sections/Footer/PoweredByDeco.tsx";
import * as $$$$$$13 from "./sections/Footer/PoweredByVtex.tsx";
import * as $$$$$$14 from "./sections/Footer/PoweredByWave.tsx";
import * as $$$$$$15 from "./sections/Header/Header.tsx";
import * as $$$$$$16 from "./sections/Images/Banner.tsx";
import * as $$$$$$17 from "./sections/Images/Carousel.tsx";
import * as $$$$$$28 from "./sections/Images/components/types/types.ts";
import * as $$$$$$18 from "./sections/Images/Deals.tsx";
import * as $$$$$$19 from "./sections/Images/FifthVariation.tsx";
import * as $$$$$$20 from "./sections/Images/FirstVariation.tsx";
import * as $$$$$$21 from "./sections/Images/FourthVariation.tsx";
import * as $$$$$$22 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$23 from "./sections/Images/SecondVariation.tsx";
import * as $$$$$$24 from "./sections/Images/SeventhVariation.tsx";
import * as $$$$$$25 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$26 from "./sections/Images/SixthVariation.tsx";
import * as $$$$$$27 from "./sections/Images/ThirdVariation.tsx";
import * as $$$$$$29 from "./sections/Institutional/About.tsx";
import * as $$$$$$30 from "./sections/Institutional/Button.tsx";
import * as $$$$$$31 from "./sections/Institutional/Faq.tsx";
import * as $$$$$$32 from "./sections/Institutional/FirstSeller.tsx";
import * as $$$$$$33 from "./sections/Institutional/Form.tsx";
import * as $$$$$$34 from "./sections/Institutional/ImageComponent.tsx";
import * as $$$$$$35 from "./sections/Institutional/Sac.tsx";
import * as $$$$$$36 from "./sections/Institutional/SecondSeller.tsx";
import * as $$$$$$37 from "./sections/Institutional/Text.tsx";
import * as $$$$$$38 from "./sections/Institutional/TimelineSeller.tsx";
import * as $$$$$$39 from "./sections/Institutional/Title.tsx";
import * as $$$$$$40 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$41 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$42 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$43 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$44 from "./sections/Product/Notfound.tsx";
import * as $$$$$$45 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$46 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$47 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$48 from "./sections/Product/ProductShelfWithTimer.tsx";
import * as $$$$$$49 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$50 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$51 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$52 from "./sections/Session.tsx";
import * as $$$$$$53 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$54 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$55 from "./sections/Spacer.tsx";
import * as $$$$$$56 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$0,
    "site/loaders/icons.ts": $$$1,
    "site/loaders/minicart.ts": $$$2,
    "site/loaders/simulateCart.ts": $$$3,
    "site/loaders/user.ts": $$$4,
    "site/loaders/wishlist.ts": $$$5,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Category/CarouselBrand.tsx": $$$$$$1,
    "site/sections/Category/CarouselCategory.tsx": $$$$$$2,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$3,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$4,
    "site/sections/Component.tsx": $$$$$$5,
    "site/sections/Content/Faq.tsx": $$$$$$6,
    "site/sections/Content/Hero.tsx": $$$$$$7,
    "site/sections/Content/Intro.tsx": $$$$$$8,
    "site/sections/Content/Logos.tsx": $$$$$$9,
    "site/sections/Content/ShowCaseCounter.tsx": $$$$$$10,
    "site/sections/Footer/Footer.tsx": $$$$$$11,
    "site/sections/Footer/PoweredByDeco.tsx": $$$$$$12,
    "site/sections/Footer/PoweredByVtex.tsx": $$$$$$13,
    "site/sections/Footer/PoweredByWave.tsx": $$$$$$14,
    "site/sections/Header/Header.tsx": $$$$$$15,
    "site/sections/Images/Banner.tsx": $$$$$$16,
    "site/sections/Images/Carousel.tsx": $$$$$$17,
    "site/sections/Images/components/types/types.ts": $$$$$$28,
    "site/sections/Images/Deals.tsx": $$$$$$18,
    "site/sections/Images/FifthVariation.tsx": $$$$$$19,
    "site/sections/Images/FirstVariation.tsx": $$$$$$20,
    "site/sections/Images/FourthVariation.tsx": $$$$$$21,
    "site/sections/Images/ImageGallery.tsx": $$$$$$22,
    "site/sections/Images/SecondVariation.tsx": $$$$$$23,
    "site/sections/Images/SeventhVariation.tsx": $$$$$$24,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$25,
    "site/sections/Images/SixthVariation.tsx": $$$$$$26,
    "site/sections/Images/ThirdVariation.tsx": $$$$$$27,
    "site/sections/Institutional/About.tsx": $$$$$$29,
    "site/sections/Institutional/Button.tsx": $$$$$$30,
    "site/sections/Institutional/Faq.tsx": $$$$$$31,
    "site/sections/Institutional/FirstSeller.tsx": $$$$$$32,
    "site/sections/Institutional/Form.tsx": $$$$$$33,
    "site/sections/Institutional/ImageComponent.tsx": $$$$$$34,
    "site/sections/Institutional/Sac.tsx": $$$$$$35,
    "site/sections/Institutional/SecondSeller.tsx": $$$$$$36,
    "site/sections/Institutional/Text.tsx": $$$$$$37,
    "site/sections/Institutional/TimelineSeller.tsx": $$$$$$38,
    "site/sections/Institutional/Title.tsx": $$$$$$39,
    "site/sections/Links/LinkTree.tsx": $$$$$$40,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$41,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$42,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$43,
    "site/sections/Product/Notfound.tsx": $$$$$$44,
    "site/sections/Product/ProductDetails.tsx": $$$$$$45,
    "site/sections/Product/ProductShelf.tsx": $$$$$$46,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$47,
    "site/sections/Product/ProductShelfWithTimer.tsx": $$$$$$48,
    "site/sections/Product/SearchResult.tsx": $$$$$$49,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$50,
    "site/sections/Product/Wishlist.tsx": $$$$$$51,
    "site/sections/Session.tsx": $$$$$$52,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$53,
    "site/sections/Social/WhatsApp.tsx": $$$$$$54,
    "site/sections/Spacer.tsx": $$$$$$55,
    "site/sections/Theme/Theme.tsx": $$$$$$56,
  },
  "actions": {
    "site/actions/minicart/submit.ts": $$$$$$$$$0,
    "site/actions/wishlist/submit.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/ai-assistants.ts": $$$$$$$$$$$0,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$1,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$2,
    "site/apps/deco/implementation.ts": $$$$$$$$$$$3,
    "site/apps/deco/typesense.ts": $$$$$$$$$$$4,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$5,
    "site/apps/site.ts": $$$$$$$$$$$6,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
